name: Create a comment on new issues

on:
  issues:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "${{ toJson(github) }}"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"

  comment-script-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;
            const body = "This is a multi-line test comment\n- With GitHub **Markdown** :sparkles:\n- Created with the GitHub API";
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body
            });
